### ISSUE TITLE
Awesome Flutter

### ISSUE THREAD

**Issue by Solido** [apatil88/FlutterDartProjects#1]
Hi !

Your repo is a very good introduction to bloc. 
Would you add a link to your article in the README and if you want you can PR 👍 https://github.com/Solido/awesome-flutter
Thanks

**Comment by apatil88** [comment]
Hello @Solido , yes I would love to. Please let me know if I can create a new section for Bloc under 'Contents' in the README.md at https://github.com/Solido/awesome-flutter

**Comment by apatil88** [comment]
Hello @Solido , Thank you for your interest. I have created a PR: https://github.com/Solido/awesome-flutter/pull/142

Please let me know if any changes are needed.

Best,
Amrut
